# Generated by Django 2.0.7 on 2018-07-13 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodGas', models.PositiveIntegerField()),
                ('DesGas', models.CharField(max_length=20)),
                ('FecGas', models.DateTimeField(auto_now_add=True)),
                ('FecDocGas', models.DateTimeField()),
                ('ValGas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.PositiveIntegerField()),
                ('Dig', models.CharField(max_length=1)),
                ('Nombre', models.CharField(max_length=35)),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.PositiveIntegerField()),
                ('Descripcion', models.CharField(max_length=25)),
                ('Tipo', models.CharField(choices=[('I', 'Ingreso'), ('G', 'Gasto')], default='I', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='gasto',
            name='Proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAdmin.Proveedor'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='Rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAdmin.Rubro'),
        ),
    ]
